language: cpp

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.9.0


matrix:
  fast_finish: true
  include:
# linux + gcc
    - os: linux
      compiler: gcc
      name: ubuntu 14.04 - gcc@5.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=g++-5 && CXX=g++-5"
        - COMPILER_ID="gcc"

    - os: linux
      compiler: gcc
      name: ubuntu 14.04 - gcc@6.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=g++-6 && CXX=g++-6"
        - COMPILER_ID="gcc"

    - os: linux
      compiler: gcc
      name: ubuntu 14.04 - gcc@7.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=g++-7 && CXX=g++-7"
        - COMPILER_ID="gcc"

    - os: linux
      compiler: gcc
      name: ubuntu 14.04 - gcc@8.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - COMPILER_ID="gcc"

  allow_failures:
    - name: ubuntu 14.04 - clang@3.6
    - name: ubuntu 14.04 - clang@3.8
    - name: ubuntu 14.04 - clang@3.9
    - name: macOS - clang@7.0


before_install:
  - travis_retry eval "${MATRIX_EVAL}"

install:
  # CMake upgrade

  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then wget --no-check-certificate https://cmake.org/files/v3.13/cmake-3.13.1-Darwin-x86_64.tar.gz   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then tar -xzf cmake-3.13.1-Darwin-x86_64.tar.gz                                                    ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export PATH=$PWD/cmake-3.13.1-Darwin-x86_64/CMake.app/Contents/bin:$PATH                      ;fi

  ###############################################################################################################################################

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$COMPILER_ID" == "gcc" ]]; then wget --no-check-certificate https://cmake.org/files/v3.13/cmake-3.13.1-Linux-x86_64.tar.gz    ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$COMPILER_ID" == "gcc" ]]; then tar -xzf cmake-3.13.1-Linux-x86_64.tar.gz                                                     ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$COMPILER_ID" == "gcc" ]]; then export PATH=$PWD/cmake-3.13.1-Linux-x86_64/bin:$PATH                                          ;fi

  - mkdir build_debug && cd build_debug
  - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DGRAPHICS=OFF
  - cd ..
  - mkdir build_release && cd build_release
  - cmake .. -DCMAKE_BUILD_TYPE="Release" -DGRAPHICS=OFF
  - cd ..

script:
  - cd build_debug && cmake --build . --target install -- -j8 && cd ..
  - cd build_release && cmake --build . --target install -- -j8 && cd ..
  - cd build_debug && ./Test && cd ..
  - cd build_release && ./Test && cd ..
